name: Self-Hosted Runner Test (Linux)

on: [push]

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Linux system info
        run: |
          echo "Running on Linux"
          uname -a
          lsb_release -a || cat /etc/os-release
          df -h
          free -m
